### ISSUE TITLE
apply命令提示error: module 'distutils' has no attribute 'util'

### ISSUE THREAD

**Issue by bestway66** [abse4411/projz_renpy_translation#15]
apply命令提示error: module 'distutils' has no attribute 'util'

**Comment by abse4411** [comment]
你好，是否能提供完整运行日志？这应该是0.38才有的apply命令，现在已经不在维护了

**Comment by bestway66** [comment]
![Uploading 1c1ed8ca0eac9b210fa67bcec8273d5.png…]()

**Comment by abse4411** [comment]
把控制台的结果文本贴上来就行

**Comment by bestway66** [comment]
What is your next step? (Enter a command (case insensitive) or Q/q to exit): 
l
there are 1 projects in ./projz
+---------------+---------+------+--------------------+----------------------+-----------------+----------+
| Project Index | Project | Tag  | Translated line(s) | Untranslated line(s) |    Source dir   | Num Rpys |
+---------------+---------+------+--------------------+----------------------+-----------------+----------+
|       0       |  mygame | v3.0 |   chinese: 25110   |    chinese: 3420     | D:\my_game\game |   1129   |
+---------------+---------+------+--------------------+----------------------+-----------------+----------+
What is your next step? (Enter a command (case insensitive) or Q/q to exit): 
apply 0
[2024-01-13 09:36:01][index.py:237, tid51216][INFO] - Selecting the default language chinese for the current operation. If you want change to another language, please specify the argument {lang}. 
[2024-01-13 09:36:01][index.py:277, tid51216][WARNING] - There still exists untranslated texts (qty:3420) in language chinese. 
error: module 'distutils' has no attribute 'util'
[2024-01-13 09:36:01][parse_console.py:138, tid51216][ERROR] - module 'distutils' has no attribute 'util' 
Traceback (most recent call last):
  File "C:/Users/thebestway66/Desktop/projz_renpy_translation-9e257770e9b30011b1053da28634c41d958d0fc5/parse_console.py", line 135, in main
    execute_cmd(cmd, *args[1:])
  File "C:\Users\thebestway66\Desktop\projz_renpy_translation-9e257770e9b30011b1053da28634c41d958d0fc5\cmd\__init__.py", line 67, in execute_cmd
    _REGISTERED_CMDS[name](*args)
  File "C:\Users\thebestway66\Desktop\projz_renpy_translation-9e257770e9b30011b1053da28634c41d958d0fc5\cmd\project.py", line 36, in apply_cmd
    proj.apply_by_default(lang, strict=strict_mode, skip_unmatch=skip_unmatch)
  File "C:\Users\thebestway66\Desktop\projz_renpy_translation-9e257770e9b30011b1053da28634c41d958d0fc5\store\index.py", line 269, in apply_by_default
    self.apply(default_config.project_path, lang, strict=strict, skip_unmatch=skip_unmatch)
  File "C:\Users\thebestway66\Desktop\projz_renpy_translation-9e257770e9b30011b1053da28634c41d958d0fc5\store\index.py", line 281, in apply
    remove_marks = default_config.remove_marks
  File "C:\Users\thebestway66\Desktop\projz_renpy_translation-9e257770e9b30011b1053da28634c41d958d0fc5\config\config.py", line 51, in remove_marks
    return distutils.util.strtobool(self.get_global('REMOVE_MARKS'))
AttributeError: module 'distutils' has no attribute 'util'
What is your next step? (Enter a command (case insensitive) or Q/q to exit):
