### ISSUE TITLE
有一些游戏无法新建任务

### ISSUE THREAD

**Issue by jsqw41** [abse4411/projz_renpy_translation#16]
n G:\AMothersLovePLUS-Part12PLUS-pc -n aml
Checking the skeleton for this RenPy game...
ERROR:root:Coundn't find a executable file file in G:\AMothersLovePLUS-Part12PLUS-pc\lib
Traceback (most recent call last):
  File ".\main.py", line 62, in main
    execute_cmd(cmd_name, cmd_line)
  File "G:\0.Translate\projz_renpy_translation-master\command\manage.py", line 77, in execute_cmd
    cmd.invoke()
  File "G:\0.Translate\projz_renpy_translation-master\command\renpy\base.py", line 44, in invoke
    index = TranslationIndex.from_dir(self.args.game_path, self.args.name, self.args.tag)
  File "G:\0.Translate\projz_renpy_translation-master\store\index.py", line 834, in from_dir
    project = Project.from_dir(project_path)
  File "G:\0.Translate\projz_renpy_translation-master\injection\renpy.py", line 235, in from_dir
    executable_path = check_python_exe(abs_path)
  File "G:\0.Translate\projz_renpy_translation-master\injection\renpy.py", line 78, in check_python_exe
    assert executable_path is not None, f'Coundn\'t find a executable file file in {lib_path}'
AssertionError: Coundn't find a executable file file in G:\AMothersLovePLUS-Part12PLUS-pc\lib

是因为这些游戏用的Renpy版本过老吗？

**Comment by abse4411** [comment]
可以提供下lib目录下有哪些文件吗，每个子目录  可以➕q 1834674034

**Comment by jsqw41** [comment]
> 可以提供下lib目录下有哪些文件吗，每个子目录 可以➕q 1834674034

嗯嗯 已+
