### ISSUE TITLE
Translator is crashed

### ISSUE THREAD

**Issue by xiaoshushu1211** [abse4411/projz_renpy_translation#28]
如果不开启renpy游戏，启动ollama，启动翻译服务器，
会报错：Translator is stopped by the user.
控制台如下：

Apply a translator: CloseAI/qwen:0.5b, translation target: Auto->Chinese
Max turn for chat is set to: 8
Release resources of the translator...
Closing the OpenAI client...
Translator is stopped by the user.

如果开启renpy界面后，启动ollama，启动翻译服务器。
会报错Translator is crashed!
控制台如下：

ERROR:root:Error code: 503
Traceback (most recent call last):
  File "local_server\index.py", line 81, in run
  File "trans\base.py", line 24, in translate_batch
  File "trans\base.py", line 24, in <listcomp>
  File "translation_provider\closeapi.py", line 33, in translate
  File "trans\openai_api\wraaper.py", line 106, in translate
  File "openai\_utils\_utils.py", line 275, in wrapper
  File "openai\resources\chat\completions.py", line 667, in create
  File "openai\_base_client.py", line 1213, in post
  File "openai\_base_client.py", line 902, in request
  File "openai\_base_client.py", line 978, in _request
  File "openai\_base_client.py", line 1026, in _retry_request
  File "openai\_base_client.py", line 978, in _request
  File "openai\_base_client.py", line 1026, in _retry_request
  File "openai\_base_client.py", line 993, in _request
openai.InternalServerError: Error code: 503
Release resources of the translator...
Closing the OpenAI client...
Translator is crashed!

----------------------
测试了qwen 0.5b，4b以及qwen2 7b。
都有以上问题
测试了lm-studio的API也是一样。
不知为何

**Comment by abse4411** [comment]
使用时关闭代理软件。

**Comment by xiaoshushu1211** [comment]
未开启代理软件，而且本地ollama可以正常run各个模型。

**Comment by abse4411** [comment]
你好，你可以尝试重新下载最新libs和exe进行重新装，目前我没有遇到这个问题。UI界面选择的模型必须是ollama list中出现的，如果没有可以手动输入，再点击应用即可。
