### ISSUE TITLE
这一连串的报错是什么情况

### ISSUE THREAD

**Issue by redball1017** [abse4411/projz_renpy_translation#31]
报错信息：
` ERROR:root:No module named 'torch'
Traceback (most recent call last):
  File "translator\__init__.py", line 24, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "translator\ai\__init__.py", line 17, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "translator\ai\impl.py", line 22, in <module>
ModuleNotFoundError: No module named 'torch'
ERROR:root:Unable to connect the Internet.

Traceback (most recent call last):
  File "urllib3\connection.py", line 198, in _new_conn
  File "urllib3\util\connection.py", line 85, in create_connection
  File "urllib3\util\connection.py", line 73, in create_connection
OSError: [WinError 10049] 在其上下文中，该请求的地址无效。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 793, in urlopen
  File "urllib3\connectionpool.py", line 491, in _make_request
  File "urllib3\connectionpool.py", line 467, in _make_request
  File "urllib3\connectionpool.py", line 1099, in _validate_conn
  File "urllib3\connection.py", line 616, in connect
  File "urllib3\connection.py", line 213, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001D6E0725430>: Failed to establish a new connection: [WinError 10049] 在其上下文中，该请求的地址无效。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 847, in urlopen
  File "urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='geolocation.onetrust.com', port=443): Max retries exceeded with url: /cookieconsentpub/v1/geo/location (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D6E0725430>: Failed to establish a new connection: [WinError 10049] 在其上下文中，该请求的地址无效。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "translators\server.py", line 333, in get_region_of_server
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='geolocation.onetrust.com', port=443): Max retries exceeded with url: /cookieconsentpub/v1/geo/location (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D6E0725430>: Failed to establish a new connection: [WinError 10049] 在其上下文中，该请求的地址无效。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connection.py", line 198, in _new_conn
  File "urllib3\util\connection.py", line 60, in create_connection
  File "socket.py", line 918, in getaddrinfo
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 793, in urlopen
  File "urllib3\connectionpool.py", line 491, in _make_request
  File "urllib3\connectionpool.py", line 467, in _make_request
  File "urllib3\connectionpool.py", line 1099, in _validate_conn
  File "urllib3\connection.py", line 616, in connect
  File "urllib3\connection.py", line 205, in _new_conn
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000001D6E073A160>: Failed to resolve 'ip.taobao.com' ([Errno 11004] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 847, in urlopen
  File "urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ip.taobao.com', port=443): Max retries exceeded with url: /outGetIpInfo (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D6E073A160>: Failed to resolve 'ip.taobao.com' ([Errno 11004] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "translators\server.py", line 340, in get_region_of_server
  File "requests\api.py", line 115, in post
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ip.taobao.com', port=443): Max retries exceeded with url: /outGetIpInfo (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D6E073A160>: Failed to resolve 'ip.taobao.com' ([Errno 11004] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "translator\api\__init__.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "translator\api\translators_impl.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "trans\translators_api\__init__.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "trans\translators_api\wraaper.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "translators\__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "translators\server.py", line 5682, in <module>
  File "translators\server.py", line 5410, in __init__
  File "translators\server.py", line 344, in get_region_of_server
translators.server.TranslatorError: Unable to connect the Internet. `

### 补充：
我也没给python代理之类的，怎么感觉好像是网络问题，不应该啊

**Comment by redball1017** [comment]
补充：开TUN代理或者给python套个代理就行了，估计是测试连接的某个网址在我这里无法连通导致程序判断我没有连接网络

**Comment by abse4411** [comment]
> 补充：开TUN代理或者给python套个代理就行了，估计是测试连接的某个网址在我这里无法连通导致程序判断我没有连接网络

运行时候有代理可能导致一些翻译器无法使用，新版本有检测这类报错并提醒用户

**Comment by redball1017** [comment]
> > 补充：开TUN代理或者给python套个代理就行了，估计是测试连接的某个网址在我这里无法连通导致程序判断我没有连接网络
> 
> 运行时候有代理可能导致一些翻译器无法使用，新版本有检测这类报错并提醒用户

但不过我出现这些报错的时候是没有给他配置代理的。是在我配置代理时这些报错才消失。这就很迷。

**Comment by abse4411** [comment]
> > > 补充：开TUN代理或者给python套个代理就行了，估计是测试连接的某个网址在我这里无法连通导致程序判断我没有连接网络
> > 
> > 
> > 运行时候有代理可能导致一些翻译器无法使用，新版本有检测这类报错并提醒用户
> 
> 但不过我出现这些报错的时候是没有给他配置代理的。是在我配置代理时这些报错才消失。这就很迷。

国内不开代理是可以正常用的，可能环境比较特殊
